### ISSUE TITLE
Ведение кода и repositories

### ISSUE THREAD

**Issue by DS-PRO-PIT-test** [DS-PRO-PIT/ds_pro_work#1]
Здрасьте.
Есть предложение выделять такие практические задания, как https://github.com/DS-PRO-PIT/ds_pro_work/tree/main/python_8 как отдельные repository.
Предпосылки - такие задания являются довольно самостоятельными единицами, поскольку имеют начальную постановку задачи и вполне ожидаемый результат.
А то, что они являются частью курса можно оформить перекрёстными ссылками в README.md

**Comment by DS-PRO-PIT** [comment]
Интересная мысль. Может в ближайшее время займусь.
